s = str(input('Введите по порядку, без пробелов, элементы кортежа: '))
t = list(s)
a = tuple(t)
print(a)
zero = t.count('0')
one = t.count('1')
two = t.count('2')
three = t.count('3')
four = t.count('4')
five = t.count('5')
six = t.count('6')
seven = t.count('7')
eight = t.count('8')
nine = t.count('9')

print("Количество 0 = "+ str(zero))
print("Количество 1 = "+ str(one))
print("Количество 2 = "+ str(two))
print("Количество 3 = "+ str(three))
print("Количество 4 = "+ str(four))
print("Количество 5 = "+ str(five))
print("Количество 6 = "+ str(six))
print("Количество 7 = "+ str(seven))
print("Количество 8 = "+ str(eight))
print("Количество 9 = "+ str(nine))